version: '3'
services:
  api-service-discovery:
    image: abatalib/api-service-discovery
    ports:
      - 8761:8761
    restart:
      on-failure
  api-service-gateway:
    image: abatalib/api-service-gateway
    depends_on:
      - api-service-discovery
    ports:
      - 9999:9999
    restart:
      on-failure
  api-famille-emploi:
    image: abatalib/api-famille-emploi
    depends_on:
      - api-service-discovery
    ports:
      - 9002:9002
    restart:
      on-failure